version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
